### ISSUE TITLE
error in execution

### ISSUE THREAD

**Issue by aremazeilles** [AdrianaTorres/Manipulation#13]
Launching the first example:

```term
./run_pi_RoM_LBT_Exo.m Range_of_movement_octave/tests/data/input/dinamica44_B.mat out 
current directory: /home/anthony/code/eurobench/csic/pi_manipulation
LBT data Exo mat : Range_of_movement_octave/tests/data/input/dinamica44_B.mat
result dir: out
error: invalid use of script /home/anthony/code/eurobench/csic/pi_manipulation/Range_of_movement_octave/src/Main_ROM_LBT_Exo.m in index expression
error: called from
    run_pi_RoM_LBT_Exo at line 20 column 1
```

I get the same error hen launched directly from Octave (except the 2 last lines that are of course not mentioned). You don't have the same issue in your environment?

Opening the file `Main_ROM_LBT_Exo.m`, effectively it is not defined as a function, which is why I guess it does not work. 
Can you confirm it does not work on you pc? 

If so, could you get inspiration from the irregular terrain repository to fix this?

**Comment by jfcarre** [comment]
I have uploaded a new version of the scripts. I have corrected some errors in the execution of the code. 

Regarding this issue, in the new version, I am able to run the code from Octavi. However, I am no able to run it from the command window. I am using Windows 10. Despite this, the structure of the main script (run_pi_RoM...) is the same as in https://github.com/AdrianaTorres/Irregular_Terrains, so it should work in the same way.

**Comment by aremazeilles** [comment]
I will try it. The command `run_pi_---` is for usage from linux, which is the platform onto which the code should work.

**Comment by jfcarre** [comment]
Did it work?

**Comment by jfcarre** [comment]
I have run every run_pi file in the powershell of Windows and everything went ok, can you confirm that the same happens in linux?

**Comment by aremazeilles** [comment]
outdated
