### ISSUE TITLE
Performance_time_octave: scripts not working

### ISSUE THREAD

**Issue by aremazeilles** [AdrianaTorres/Manipulation#3]
Assuming I should be looking at the files tagged octave in [octave folder](https://github.com/AdrianaTorres/Manipulation/tree/master/Performance_Time_octave/src). 
Launching them (octave 4.2.2), I get the following errors:

```octave
TimeLBTExo_octave
error: TimeLBTExo_octave: =: nonconformant arguments (op1 is 1x1, op2 is 1x0)
error: called from
    TimeLBTExo_octave at line 63 column 22

TimeLBTWithout_octave
error: locs(2): out of bound 1
error: called from
    TimeLBTWithout_octave at line 35 column 21

TimeSagittalLifting_octave
error: idx_flat(0): subscripts must be either integers 1 to (2^31)-1 or logicals
error: called from
    TimeSagittalLifting_octave at line 148 column 7
```

Could you confirm me whether these scripts work for you?

**Comment by aremazeilles** [comment]
ping @DavidPintoFernandez

**Comment by DavidPintoFernandez** [comment]
Adriana is working on that. Please @AdrianaTorres provide feedback when you solve this.

**Comment by AdrianaTorres** [comment]
I have started working on the Irregular Terrain code, which I'm more familiarized with and I'm almost about to finish. As soon I finish with it I will start working on this code and solve all the issues.

**Comment by aremazeilles** [comment]
ok, no prb, we can start with the other repository

**Comment by aremazeilles** [comment]
@jfcarre I guess this will be processed after the range of movement.

**Comment by aremazeilles** [comment]
outdated
