### ISSUE TITLE
Octave vs Matlab code

### ISSUE THREAD

**Issue by aremazeilles** [AdrianaTorres/Manipulation#5]
Did you experience the need of having such different code in between the octave and matlab version? Wouldn't it be possible to have a common code, in which we only adjust some specific function that may not be present from matlab to octave? Having two different files requires maintaining each of them separately, double effort.

**Comment by aremazeilles** [comment]
ping @DavidPintoFernandez

**Comment by DavidPintoFernandez** [comment]
We are trying to merge all code in octave. Here we mixed both, but we will maintain only the octave code. We have no experience at all on octave, so we are working slow.

**Comment by DavidPintoFernandez** [comment]
@AdrianaTorres ping

**Comment by AdrianaTorres** [comment]
The code for this scenario has been done by a degree student. We uploaded the Matlab code until we have Octave's working. In that moment, the Matlab code will be deleted and the Octave one will be the one we will be using.

**Comment by aremazeilles** [comment]
ok, so I think we can close that issue then
