### ISSUE TITLE
Range of movement: readme doc

### ISSUE THREAD

**Issue by aremazeilles** [AdrianaTorres/Manipulation#8]
Like for [irregular_terrain](https://github.com/AdrianaTorres/Irregular_Terrains#usage), we need to see in the REadme file info on how to use the code.
In particular, it is mandatory to provide some eample of how to call the programme. 
In the other repo, we provide example from Octave, and then using the script. 

Could you do so? the src folder of range of movement contains quite a lot of files, so it is not straightforward which one is the entry point.

**Comment by jfcarre** [comment]
@aremazeilles I have changed the README file. It was initially placed in the `./Manipulation` folder, but it is already in `./Manipulation/Range_of_movement_octave`.
Please, tell me if the description is enough to know how to run the script.

**Comment by aremazeilles** [comment]
The good practice is to put such information at the root of the repository. This way, the information is directly presented on the github repo, when you access to https://github.com/AdrianaTorres/Manipulation. So I would rather bring the information there, to the root readme.

 Then, looking at the information in Range_of_movement_octave/REadme.md:

_The files "Main_ROM_XXXX.m" are those that must be run. Each of the files calls to the necessary functions for calculation of the Range of Movement for each experiment: Sagittal Lifting, LBT with Exo, LBT without Exo._

I would ask you to follow the same methodology like in the readme of irregular terrain: provide a complete example of all scripts that needs to be launched to get the computation. Like this at least:

```octave
addpath("Margin_Stability_octave/src")
addpath("Tools/src")
# For the Margin stability computation
marginStability_calculation("Margin_Stability_octave/tests/data/input/COM_plano01.csv", "Margin_Stability_octave/tests/data/input/gaitEvents_plano01.csv", "Margin_Stability_octave/tests/data/input/FeetTrajectories_plano01.csv", "Margin_Stability_octave/tests/data/input/Anthropometry.yaml", "output")
```

Just do it for now for range of movement. Thanks

**Comment by jfcarre** [comment]
I have modified the README file in order to be similar to the one at Irregular Terrain. Please check if it is correct.

**Comment by aremazeilles** [comment]
Be carefull: in your version there is no `addpath("Tools/src")`. Also some file names are not correct.

**Comment by jfcarre** [comment]
It is already added. Which file names are not correct?

**Comment by aremazeilles** [comment]
Sorry, names might be good. What was misleading me is that the order in between the octave example (exo, without, sagital) is different to the order for the script example (sagital, exo, without).

And actually, file `Dinamica44_B.mat` is mentioned, but all mat files start with minor d.

**Comment by jfcarre** [comment]
Changed. Is it already correct?

**Comment by aremazeilles** [comment]
now is fine, thanks
