### ISSUE TITLE
range of movement: entry script

### ISSUE THREAD

**Issue by aremazeilles** [AdrianaTorres/Manipulation#9]
To be generic, all PI should provide some entries script.
For octave, an example can be seen [there](https://github.com/AdrianaTorres/Irregular_Terrains/blob/master/run_pi_variability):

This file can be placed at the root of the repository for instance. MAe sure adjusting the add_path in it.

This function is just the entry point that then will call the main function of the computation. It is mandatory to list all input files, and to use as last parameters the name of a folder where result files should be written.

You should not assume any location for the result file, like in [here](https://github.com/AdrianaTorres/Manipulation/blob/a69890ea467c6a8b3cdacb9e1545cbb5ccbff10c/Range_of_movement_octave/src/Main_ROM_LBT_Exo.m#L15). You should have the output folder as input parameter of your script, and do something like [here](https://github.com/AdrianaTorres/Irregular_Terrains/blob/45a93f1f0a47d24626fddf1d95420c64903a05fc/Variability_octave/src/variability_calculation.m#L94)

**Comment by jfcarre** [comment]
@aremazeilles I have added the files

**Comment by aremazeilles** [comment]
Great thanks. Merged
